# docker-compose.yml
version: '3'
services:
  server:
    image: ghcr.io/gohugoio/hugo:latest
    container_name: hugo-blog
    tty: true
    command: server --bind 0.0.0.0 --port 1313 --buildDrafts --buildFuture --renderToMemory
    working_dir: /src
    user: "1000:1000"
    volumes:
      - ".:/src"
    ports:
      - "1313:1313"
